course_work/routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use \Symfony\Component\Console\Input\Input;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('user', 'UsersController');
Route::resource('product', 'ProductsController');

Route::post('/search/{search}', 'SearchController@index')->name('search.index');
Route::match(['get','post'],'/product/create/{cat}','ProductsController@onchange')->name('product.onchange');

course_work/app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    //
    protected $table = 'products';
    protected $primaryKey = 'id';
    public $isIncrement = true;
    public $timestamps = true;

    public function category()
    {
        # code...
        return $this->belongsTo('App\Category');
    }

    public function tags()
    {
        return $this->belongsToMany('App\Tag','tags_products');
    }

    public function image()
    {
        return $this->belongsTo('App\Image');
    }

}

course_work/app/Http/Controllers/ProductsController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Product;
use App\Tag;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class ProductsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $reqest)
    {
        //
        $products = Product::with(['tags','tags.param','category','image'])->get();
//        print_r($products->first());die;
        return view('products/index',['products' => $products]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        //
        $categories = DB::table('categories')->get();

        return view('products/create_product_form',['categories'=>$categories,'cur_tags' => null]);
    }

    public function onchange(Request $request, $cat = null)
    {
        $categories = DB::table('categories')->get();


        if($cat != '')
        {
            $tags = DB::table('tags')
                ->join('params','params.id','=','tags.param_id')
                ->join('categories','categories.id','=','params.category_id')
                ->select('tags.title as tag_title','categories.title as category_name','tags.id')
                ->where('categories.title','=',"$cat")
                ->get();
//
            $data = [$request->input(), 'cat' => $cat];
            return view('products/create_product_form',['categories'=>$categories,'cur_tags' => $tags,'cat' => $cat]);
        }

        print_r($cat);die;
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, $data = null)
    {
        //

        print_r($request->all());

        return redirect()->route('product.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product,Request $request)
    {
        //
        $item = Product::where('products.id','=',$product->id)->get();
//        print_r($item->first()->id);die;
        return view('products/item',['product' => $item->first()]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        //
    }



}

course_work/resources/views/products/add_tags.blade.php
@extends('layouts.app')

@section('content')
    @guest
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
            </li>

            @if (Route::has('register'))
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                </li>
            @endif
        </ul>
    @else
        <div class="container">

            <form action="{{ route('product.store',['data' => $data]) }}" method="post" enctype="multipart/form-data">
                @csrf
                @php
                    print_r($data);
                @endphp
                <div class="form-group row">
                    <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                    <div class="col-md-6">
                        <input id="name" type="text" readonly="true" class="form-control @error('name') is-invalid @enderror" name="" value="{{ $data['n'] }}" required autocomplete="name" autofocus>

                        @error('name')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="form-group row">
                    <label for="model" class="col-md-4 col-form-label text-md-right">{{ __('Model') }}</label>

                    <div class="col-md-6">
                        <input id="model" type="text" readonly="true" class="form-control @error('model') is-invalid @enderror" name="" value="{{ $data['m'] }}" required autocomplete="model" autofocus>

                        @error('model')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="form-group row">
                    <label for="price" class="col-md-4 col-form-label text-md-right">{{ __('Price') }}</label>

                    <div class="col-md-6">
                        <input id="price" type="text" readonly="true" class="form-control @error('price') is-invalid @enderror" name="" value="{{ $data['p'] }}" required autocomplete="price" autofocus>

                        @error('price')
                        <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="form-group row">
                    <label for="price" class="col-md-4 col-form-label text-md-right">{{ __('Category') }}</label>

                    <div class="col-md-6">
                        <input id="category" readonly="true" type="text" class="form-control @error('category') is-invalid @enderror" name="" value="{{ $data['c'] }}" required autocomplete="category" autofocus>

                        @error('category')
                        <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>


                <div class="form-group row">
                    <button type="submit" class="btn btn-primary btn-lg col-md-6" style=" margin-left: 33.5%;" >Submit</button>
                </div>
            </form>
        </div>
    @endguest

    <script type="text/javascript">
        function setTags(val,id,inp_id)
        {
            el = document.getElementById(id);
            val_el = document.getElementById(inp_id);

            console.log(val_el);
            if(el.checked == true){
                val_el.setAttribute('value',val);
                console.log(val_el.value);
            }else {
                val_el.setAttribute('value','');
            }
        }
    </script>
@endsection

course_work/resources/views/products/create_product_form.blade.php
@extends('layouts.app')

@section('content')
    @guest
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
            </li>

            @if (Route::has('register'))
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                </li>
            @endif
        </ul>
    @else
        <div class="container">

            <form action="{{route('product.store')}}" method="post" enctype="multipart/form-data">
                @csrf
{{--                <span>{{print_r($cat)}}</span>--}}
                <div class="form-group row">
                    <label for="name" class="col-md-4 col-form-label text-md-right text-light">{{ __('Name') }}</label>

                    <div class="col-md-6">
                        <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="n" value="{{ old('name') }}" required autocomplete="name" autofocus>

                        @error('name')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="form-group row">
                    <label for="model" class="col-md-4 col-form-label text-md-right text-light">{{ __('Model') }}</label>

                    <div class="col-md-6">
                        <input id="model" type="text" class="form-control @error('model') is-invalid @enderror" name="m" value="{{ old('model') }}" required autocomplete="model" autofocus>

                        @error('model')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="form-group row">
                    <label for="price" class="col-md-4 col-form-label text-md-right text-light">{{ __('Price') }}</label>

                    <div class="col-md-6">
                        <input id="price" type="text" class="form-control @error('price') is-invalid @enderror" name="p" value="{{ old('price') }}" required autocomplete="price" autofocus>

                        @error('price')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
{{--                @php--}}
{{--                    print_r($categories);--}}
{{--                @endphp--}}

                <div class="form-group row">
                    <label for="price" class="col-md-4 col-form-label text-md-right text-light">{{ __('Category') }}</label>

                    <div class="col-md-6 d-flex">
                        <div class="dropdown">
                            <button name="c" value="Category" class="btn btn-secondary dropdown-toggle" type="button" id="category-btn" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {{ $cat ?? 'Categories' }}
                            </button>
                            <div class="dropdown-menu bg-secondary" aria-labelledby="category-btn">
                                @foreach($categories as $category)
                                    @if($category->parent_id == 0)
                                        <li class="active">
                                            <a class="dropdown-item bg-secondary text-light" id="cat-{{$category->id}}" href="{{ route('product.onchange',['cat' => $category->title]) }}">{{$category->title}}</a>
                                            <ul class="collapse list-unstyled" id="cat-{{$category->id}}" style='margin-bottom: 0 !important;'>
                                                @foreach($categories as $child_category)
                                                    @if($category->id == $child_category->parent_id)
                                                        <a id="cat-{{$child_category->id}}" type="submit" href="{{ route('product.onchange',['cat' => $child_category->title]) }}" class="dropdown-item bg-secondary bg-darker-1 text-light" style="padding-left: calc(var(--link-default-padding) + 15px) !important;">
                                                            {{$child_category->title}}
                                                        </a>
                                                    @endif
                                                @endforeach
                                            </ul>
                                        </li>
                                    @endif
                                @endforeach
                            </div>
                        </div>

                    </div>
                </div>

                <div class="form-group row">
                    <label for="price" class="col-md-4 col-form-label text-md-right">{{ __('Tags') }}</label>
                    <div class="col-md-6 d-flex">
                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="tag-1-btn" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Tags
                            </button>

                            <div class="dropdown-menu bg-secondary" aria-labelledby="tag-1-btn">
                                @if($cur_tags != null)
                                    @foreach($cur_tags as $tag)
                                        <div class="dropdown-item bg-secondary text-light">
                                            <input id="tag-val-{{$tag->id}}" type="text" name="t-{{$tag->id}}" class="bg-secondary text-light" hidden="true" >
                                            <input id="cb-{{$tag->id}}" type="checkbox" class="bg-secondary text-light" onchange="setTags('{{$tag->tag_title}}','cb-{{$tag->id}}','tag-val-{{$tag->id}}')" value="{{$tag->tag_title}}" >
                                            <a href="#"  class="bg-secondary bg-darker-1 text-light" id="tag-{{$tag->id}}" href="{{'#'}}" onclick="change('tag-{{$tag->id}}','tag-1-btn')">
                                                {{$tag->tag_title}}
                                            </a>
                                        </div>
                                    @endforeach
                                @endif
                            </div>
                        </div>
                    </div>
                </div>

                <div class="form-group row">
                    <label for="image" class="col-md-4 col-form-label text-md-right text-light">{{ __('Image') }}</label>

                    <div class="col-md-6">
                        <input type="file" name="image">


                            @error('description')
                            <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror

                    </div>
                </div>
                <div class="form-group row">
                    <label for="description" class="col-md-4 col-form-label text-md-right text-light">{{ __('Description') }}</label>

                    <div class="col-md-6">
                        <textarea id="description" type="text" rows="7" class="form-control @error('description') is-invalid @enderror" name="des" value="{{ old('description') }}" style="resize: none;" required autocomplete="description" autofocus>
                        </textarea>
                        @error('description')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
                <div class="form-group row">
                    <button type="submit" class="btn btn-primary btn-lg col-md-6" style=" margin-left: 33.5%;" >Submit</button>
                </div>
            </form>
        </div>

        <script type="text/javascript">
            function change(e,b){
                // console.log(e,b);

                text = document.getElementById(`${e}`).textContent;
                btn = document.getElementById(b);
                inp = document.getElementById('category');

                // console.log(e,b);
                // console.dir(btn);

                btn.textContent = text.replace(/[\n\r]+|[\s]{2,}/g, ' ').trim();
                btn.value = btn.textContent;
                inp.value = btn.textContent;
            }

            function tmp()
            {

            }


        </script>
    @endguest
@endsection

course_work/resources/views/products/index.blade.php
@extends('layouts.app')

@section('content')
    @if($products->first()['id'] != null)
        @foreach ($products as $product)
            @if($product != null || $product != '')
                <div class="card" style="width: 18rem;margin: 0 0.5rem 1rem">
                    <img class="card-img-top" src="{{$product->image == null ? url('/images/placeholder.png') : url("/images/{$product->image->file}")}}" alt="Card image cap">
                    <div class="card-body" style="display: flex;flex-direction: column;justify-content: flex-end;">
                        <h5 class="card-title ">{{$product->name}}</h5>
                        <p class="card-text text-dark">Category: {{$product->category['title']}}</p>
                        @foreach($product->tags as $tag)
                            <p class="card-text text-dark">{{$tag->param['title']}}: {{$tag['title']}}</p>
                        @endforeach
                    </div>
                    <a href="{{route('product.show',$product->id)}}" class="btn btn-primary">Go somewhere</a>
                </div>
            @endif
        @endforeach
    @else
        <h1 class="text-light">Have no items</h1>
    @endif
@endsection

@section('sidebar')
    <nav id="sidebar" class="bg-dark bg-darker-3">
        <div class="sidebar-header bg-dark">
            <button type="button" id="sidebarCollapse" class="btn btn-info" style="width: 100%;" onclick="sidebarToggle()">
                <i class="fas fa-align-left"></i>
                <span id="btn-toggle-span">Toggle Sidebar</span>
            </button>
            <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fas fa-align-justify"></i>
            </button>
        </div>

        <ul class="list-unstyled components">
            <li class="active">
                <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                    <i class="fas fa-home"></i>
                    Categories
                </a>
                <ul class="collapse list-unstyled" id="homeSubmenu">
                    @foreach($categories as $category)
                        @if($category->parent_id == 0 )
                            <li class="active">
                                <a href="#cat-{{$category->id}}" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle collapsed">
                                    {{$category->title}}
                                </a>
                                <ul class="list-unstyled collapse" id="cat-{{$category->id}}">
                                    @foreach($categories as $child_category)
                                        @if($category->id == $child_category->parent_id)
                                            <li>
                                                <a href="{{route('search.index',['_token='=>csrf_token(),'query' => $child_category->title])}}" aria-expanded="false" class="bg-darker-3" style="padding-left: calc(var(--link-default-padding) + 15px) !important;">
                                                        {{$child_category->title}}
                                                </a>
                                            </li>
                                        @endif
                                    @endforeach
                                </ul>
                            </li>
                        @endif
                    @endforeach
                </ul>
            </li>
            <li>
                <a href="#tagsSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                    <i class="fas fa-copy"></i>
                    Tags
                </a>
                <ul class="collapse list-unstyled" id="tagsSubmenu">
                    @foreach($tags as $tag)
                    <li>
                        <a href="#" aria-expanded="false" class="bg-darker-3" style="padding-left: calc(var(--link-default-padding) + 15px) !important;">
                            <i class="fas fa-hashtag"></i>{{$tag->title}}
                        </a>
                    </li>
                    @endforeach
                </ul>
            </li>
            <li>
                <a href="#">
                    <i class="fas fa-question"></i>
                    FAQ
                </a>
            </li>
            <li>
                <a href="#">
                    <i class="fas fa-paper-plane"></i>
                    Contact
                </a>
            </li>
        </ul>
    </nav>
@endsection

course_work/resources/views/products/item.blade.php
@extends('layouts.app')

@section('content')
    <img src="{{url("images/{$product->image->file}")}}" style="width: 20%;height: 20%">
    <div class="container">
        <div class="form-group row">
            <label for="name" class="col-md-4 col-form-label text-md-right text-light">{{ __('Name') }}</label>

            <div class="col-md-6">
                <label for="name" class="col-md-4 col-form-label text-md-left text-light">{{ $product->name }}</label>
            </div>
        </div>
        <div class="form-group row">
            <label for="name" class="col-md-4 col-form-label text-md-right text-light">{{ __('Model') }}</label>

            <div class="col-md-6">
                <label for="name" class="col-md-4 col-form-label text-md-left text-light">{{ $product->model }}</label>
            </div>
        </div>
        <div class="form-group row">
            <label for="name" class="col-md-4 col-form-label text-md-right text-light">{{ __('Price') }}</label>

            <div class="col-md-6">
                <label for="name" class="col-md-4 col-form-label text-md-left text-light">{{ "$product->price$" }}</label>
            </div>
        </div>
        <div class="form-group row">
            <label for="name" class="col-md-4 col-form-label text-md-right text-light">{{ __('Description') }}</label>

            <div class="col-md-6">
                <label for="name" class="col-md-4 col-form-label text-md-left text-light">{{ "$product->description" }}</label>
            </div>
        </div>
        <div class="form-group row">
            <label for="name" class="col-md-4 col-form-label text-md-right text-light">{{ __('Category') }}</label>

            <div class="col-md-6">
                <label for="name" class="col-md-4 col-form-label text-md-left text-light">{{ $product->category->title }}</label>
            </div>
            @foreach($product->tags as $tag)
                <label for="name" class="col-md-4 col-form-label text-md-right text-light">{{ $tag->param['title']}}</label>

                <div class="col-md-6">

                    <label for="name" class="col-md-4 col-form-label text-md-left text-light">{{$tag['title']}}</label>
                </div>
            @endforeach
        </div>
    </div>
@endsection